//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstHWtrains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sit
    {
        public int Id { get; set; }
        public int SitNum { get; set; }
        public int trainID { get; set; }
        public int TrainId1 { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
